name: CI-CD-Pipeline

on:
  push:
    branches:
      - release
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: npm test

  deploy-web:
    needs: test-app
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Criar arquivo .env
        run: echo "EXPO_PUBLIC_TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" > .env

      - name: Exportar app web
        run: npx expo export --platform web

      - name: Desativar Jekyll
        run: touch dist/.nojekyll

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Fazer upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4